// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	models "backend/internal/models"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Cache is an autogenerated mock type for the Cache type
type Cache struct {
	mock.Mock
}

// GetByOriginalLink provides a mock function with given fields: ctx, link
func (_m *Cache) GetByOriginalLink(ctx context.Context, link models.OriginalLink) (models.ShortCode, error) {
	ret := _m.Called(ctx, link)

	if len(ret) == 0 {
		panic("no return value specified for GetByOriginalLink")
	}

	var r0 models.ShortCode
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.OriginalLink) (models.ShortCode, error)); ok {
		return rf(ctx, link)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.OriginalLink) models.ShortCode); ok {
		r0 = rf(ctx, link)
	} else {
		r0 = ret.Get(0).(models.ShortCode)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.OriginalLink) error); ok {
		r1 = rf(ctx, link)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByShortCode provides a mock function with given fields: ctx, code
func (_m *Cache) GetByShortCode(ctx context.Context, code models.ShortCode) (models.OriginalLink, error) {
	ret := _m.Called(ctx, code)

	if len(ret) == 0 {
		panic("no return value specified for GetByShortCode")
	}

	var r0 models.OriginalLink
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.ShortCode) (models.OriginalLink, error)); ok {
		return rf(ctx, code)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.ShortCode) models.OriginalLink); ok {
		r0 = rf(ctx, code)
	} else {
		r0 = ret.Get(0).(models.OriginalLink)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.ShortCode) error); ok {
		r1 = rf(ctx, code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Set provides a mock function with given fields: ctx, link, code
func (_m *Cache) Set(ctx context.Context, link models.OriginalLink, code models.ShortCode) error {
	ret := _m.Called(ctx, link, code)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, models.OriginalLink, models.ShortCode) error); ok {
		r0 = rf(ctx, link, code)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewCache creates a new instance of Cache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *Cache {
	mock := &Cache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
